# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies Api
      run: dotnet restore ./RentalCar.Security.API/RentalCar.Security.API.csproj

    - name: Restore dependencies Unit Test
      run: dotnet restore ./RentalCar.Security.UnitTests/RentalCar.Security.UnitTests.csproj
      
    - name: Build Api
      run: dotnet build ./RentalCar.Security.API/RentalCar.Security.API.csproj --no-restore
      
    - name: Build unit Test
      run: dotnet build ./RentalCar.Security.UnitTests/RentalCar.Security.UnitTests.csproj --no-restore
      
    - name: Test
      run: dotnet test ./RentalCar.Security.UnitTests/RentalCar.Security.UnitTests.csproj --no-build --verbosity normal
